### ISSUE TITLE
Set up the GraphQL

### ISSUE THREAD

**Issue by AnastasiaPromtep** [lapoissonnerie/touiteur-api#5]
Set up the GraphQL architecture(?)
Since we are using Apollo server we could use this package: apollo-server-express
This issue may need a working database before

**Comment by maximelouet** [comment]
We can use PostgreSQL as a database because it's very reliable and popular.
I suggest we get inspiration from this repository: https://github.com/the-road-to-graphql/fullstack-apollo-express-postgresql-boilerplate , especially for the `src` subdirectories such as `models`, `resolvers` and `schema`. I'm interested to do this.

**Comment by maximelouet** [comment]
We should take a look at https://www.prisma.io/ as well. It seems it can be used as an ORM in conjunction with Apollo. It's very sexy :eggplant:

**Comment by maximelouet** [comment]
Also, @AnastasiaPromtep did you say you wanted to use TypeScript as much as possible? We should agree on this now before going forward.
